/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SporcuRouteImport } from './routes/sporcu'
import { Route as IndexRouteImport } from './routes/index'

const SporcuRoute = SporcuRouteImport.update({
  id: '/sporcu',
  path: '/sporcu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sporcu': typeof SporcuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sporcu': typeof SporcuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sporcu': typeof SporcuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sporcu'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sporcu'
  id: '__root__' | '/' | '/sporcu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SporcuRoute: typeof SporcuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sporcu': {
      id: '/sporcu'
      path: '/sporcu'
      fullPath: '/sporcu'
      preLoaderRoute: typeof SporcuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SporcuRoute: SporcuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
